version: 2
jobs:
  build:
    working_directory: ~/sudonmul
    docker:
      - image: node:8.2.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dep-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and test
          command: npm test
      - save_cache:
          key: dep-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
